### ISSUE TITLE
Confusion about R-CNN loss of localization

### ISSUE THREAD

**Issue by lhCheung1991** [linmx0130/ya_mxdet#13]
@linmx0130 
Hi, 

I notice that you not only compute the Smooth-L1 loss between the proposal and true positive GT box, but also compute the loss between proposal and 0, for the same proposal. What's the purpose of this modification? 

`mask = (rcnn_cls_target > 0).reshape((rcnn_cls_target.shape[0], 1)).broadcast_to((rcnn_cls_target.shape[0], 4*cfg.num_classes))`
`rcnn_loss_reg = mx.nd.sum(mx.nd.smooth_l1((rcnn_reg - rcnn_reg_target) * mask, 1.0)) / mx.nd.sum(mask)`

The foreground line mask in `mask` is all 1 here.

**Comment by linmx0130** [comment]
The `mask` here is to make sure that the regression term is trained on only foreground (`rcnn_cls_target > 0`), but not background.
