### ISSUE TITLE
set_dense_weights(self.fc6, vgg16.classifier[0]) AttributeError: 'VGG' object has no attribute 'classifier'

### ISSUE THREAD

**Issue by LamHoCN** [linmx0130/ya_mxdet#5]
Hey,man,how can i solve it?
i try to modify version of mxnet to 0.12.0 but it's useless.

**Comment by linmx0130** [comment]
I'm sorry that mxnet has changed its interface... I will fix it, wait a moment.

**Comment by linmx0130** [comment]
You may pull the latest master and use latest mxnet-cu80/75 (1.0.0post) to solve this problem.

It is caused by MXNet... They changed interface of VGG.

**Comment by LamHoCN** [comment]
okey  i will try it, thx a lot.
