### ISSUE TITLE
Runtimewarning and nan errors with bbox_pred

### ISSUE THREAD

**Issue by ifeherva** [linmx0130/ya_mxdet#7]
I am getting Nan when computing the nsm:
nms.py:21: RuntimeWarning: invalid value encountered in true_divide
  iou = inter / outer
nms.py:37: RuntimeWarning: invalid value encountered in less
Which returns nan losses in the end. I see negative values in my bbox_pred wonder if that is meant to be like that.

**Comment by linmx0130** [comment]
I think it can be solved by adding an epsilon term to outer like this
`iou = inter / (outer + 1e-5)`
