### ISSUE TITLE
训练时候RCNN损失

### ISSUE THREAD

**Issue by roachsinai** [linmx0130/ya_mxdet#8]
我看Fast-RCNN论文中检测框的损失是，

![2018-04-09 15-02-19](https://user-images.githubusercontent.com/9500049/38483888-1d3e9d48-3c07-11e8-904e-ae0b2161460a.png)

也就是只计算正确类别的预测和和groundtruth bbox的损失。但是，看你实现的时候还计算了预测错误的和0值的损失，是这样么？

```
# rpn_proposal.py
# proposal_train函数下
reg_large_target = mx.nd.zeros((reg_target.shape[0], 4 * cfg.num_classes), ctx)

# train_faster_rcnn.py
rcnn_loss_reg = mx.nd.sum(mx.nd.smooth_l1((rcnn_reg - rcnn_reg_target) * mask, 1.0)) / mx.nd.sum(mask)
```

**Comment by roachsinai** [comment]
另外，还有一点儿就是

```
# rpn_proposal.py
# proposal_train函数下

# append ground truth
rpn_bbox_pred = mx.nd.concatenate([rpn_bbox_pred, gt[0][:,:4]])
```

这里面对于预测的结果为什么要加上groundtruth呢？谢谢。

**Comment by linmx0130** [comment]
1. 关于第一点，那个mask就是把预测错误的loss排除掉
2. 这个比较tricky，是根据Faster RCNN原始caffe代码写的，只所以必须加，是为了确保一定有正确的框被传给后面的模型，才能够保证RCNN的正常训练。刚开始的时候RPN输出很差，必须依靠添加ground truth补充一些正样本。

**Comment by roachsinai** [comment]
@linmx0130 谢谢回复。第二点明白了。

对于第一点，还是有疑惑。

```
# train_faster_rcnn.py
rcnn_loss_reg = mx.nd.sum(mx.nd.smooth_l1((rcnn_reg - rcnn_reg_target) * mask, 1.0)) / mx.nd.sum(mask)
```

上面这行代码中，`rcnn_reg, rcnn_reg_target, mask`的最后一维的元素在VOC数据中应该都是84个吧？

`mask`的84个元素全True或者全False，`rcnn_reg_target`中有80个0值，那这样不是`rcnn_reg`中有80个元素和0值相减了么？

因为笔记本只有个2G显卡，没有办法运行到这里设置断点单步调试。所以如果上面哪里想的不对，麻烦提醒一下。:-(

**Comment by roachsinai** [comment]
给电脑添加了增大了交换分区，用cpu跑了几张图片看输出确实是mask一行确实全1或者全0呢。

**Comment by linmx0130** [comment]
我这周检查一下，谢谢您提出的这个问题！

**Comment by roachsinai** [comment]
嗯嗯，麻烦了。

**Comment by linmx0130** [comment]
很抱歉前段时间在忙毕业论文，今天终于有时间检查。
这里的mask的shape是 batch *  anchors_count * f_height *  f_width * 4
所以每行只有4个，这个实现和原始的faster rcnn是不一样的。
